### ISSUE TITLE
get_connection hangs if the pool name doesn't exist

### ISSUE THREAD

**Issue by bigkevmcd** [erlware/episcina#9]
https://github.com/erlware/episcina/blob/master/src/epna_pool.erl#L86

This should probably use gproc:await/2

I'm happy to roll a fix if this seems reasonable?

**Comment by waisbrot** [comment]
Was this bug fixed by #10? Or was that a separate issue?

**Comment by bigkevmcd** [comment]
Yip, just checked that this now errors appropriately... thanks for the fix @omarkj :-)
